# Generated by Django 4.1.5 on 2023-02-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_text', models.CharField(max_length=255)),
                ('menu_link', models.CharField(max_length=255)),
            ],
        ),
    ]
