# Generated by Django 4.1.5 on 2023-01-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ctb_Emp_Address',
            fields=[
                ('employer_id', models.DecimalField(decimal_places=0, max_digits=14)),
                ('adtype_id', models.DecimalField(decimal_places=0, max_digits=3)),
                ('address_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('from_date', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('to_date', models.CharField(max_length=10)),
                ('entry_by', models.CharField(max_length=30)),
                ('entry_date', models.DateField()),
                ('r_status', models.CharField(max_length=1)),
                ('tran_no', models.DecimalField(decimal_places=0, max_digits=14)),
            ],
            options={
                'verbose_name_plural': 'Ctb_Person_Addresses',
            },
        ),
        migrations.CreateModel(
            name='Ctb_Emp_Contact',
            fields=[
                ('employer_id', models.DecimalField(decimal_places=0, max_digits=14)),
                ('adtype_id', models.DecimalField(decimal_places=0, max_digits=3)),
                ('address_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('a_from_date', models.CharField(max_length=10)),
                ('ctype_id', models.DecimalField(decimal_places=0, max_digits=3)),
                ('from_date', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('c_value', models.CharField(max_length=100)),
                ('to_date', models.CharField(max_length=10)),
                ('entry_by', models.CharField(max_length=30)),
                ('entry_date', models.DateField()),
                ('r_status', models.CharField(max_length=1)),
                ('tran_no', models.DecimalField(decimal_places=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Ctb_Emp_Doc',
            fields=[
                ('employer_id', models.DecimalField(decimal_places=0, max_digits=14)),
                ('doc_id', models.DecimalField(decimal_places=0, max_digits=3)),
                ('from_date', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('to_date', models.CharField(max_length=10)),
                ('issue_no', models.CharField(max_length=60)),
                ('issue_date', models.CharField(max_length=10)),
                ('issue_place', models.CharField(max_length=100)),
                ('entry_by', models.CharField(max_length=30)),
                ('entry_date', models.DateField()),
                ('r_status', models.CharField(max_length=1)),
                ('tran_no', models.DecimalField(decimal_places=0, max_digits=14)),
                ('docfile', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Ctb_Emp_Official',
            fields=[
                ('employer_id', models.DecimalField(decimal_places=0, max_digits=14)),
                ('e_id', models.DecimalField(decimal_places=0, max_digits=14)),
                ('post_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('from_date', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('to_date', models.CharField(max_length=10)),
                ('entry_by', models.CharField(max_length=30)),
                ('entry_date', models.DateField()),
                ('r_status', models.CharField(max_length=1)),
                ('tran_no', models.DecimalField(decimal_places=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Ctb_Employer',
            fields=[
                ('employer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employer_name_nep', models.CharField(max_length=150)),
                ('employer_name_eng', models.CharField(max_length=150)),
                ('e_ssid', models.CharField(max_length=25)),
                ('entry_by', models.CharField(max_length=30)),
                ('entry_date', models.DateField()),
                ('r_status', models.CharField(max_length=1)),
                ('tran_no', models.DecimalField(decimal_places=0, max_digits=14)),
                ('alert_source', models.CharField(max_length=11)),
                ('alt_source_val', models.CharField(max_length=100)),
                ('short_menu', models.CharField(max_length=1)),
                ('calendar', models.CharField(max_length=1)),
                ('group_applied', models.CharField(max_length=1)),
            ],
        ),
    ]
